#!/bin/sh
cd src/cpp/KLexpansionSolver/UQTk_v2.1.1/config
cp config.mac-xiao config.site
cd -

cd src/cpp/KLexpansionSolver/UQTk_v2.1.1
make
cd -

cd src/cpp/KLexpansionSolver/klSolver
make
cd -

. ~/.openfoam23x

cd src/foam/preTauFoam/chPressureGrad
wmake
cd -
cd src/foam/preTauFoam/
wmake
cd -

cd src/foam/tauFoam/chPressureGrad
wmake
cd -
cd src/foam/tauFoam/
wmake
cd -

cd src/foam/getObsMatrix
wmake
cd -


# ----------------------------------------------------------------- end-of-file
